---
- name: Prepare nginx
  hosts: nginx
  become: true
  tasks:
    - name: Add an Apt signing keys
      apt_key:
        url: "{{ item }}"
        state: present
      with_items:
        - https://nginx.org/keys/nginx_signing.key

    - name: Add repositories into sources list
      apt_repository:
        repo: "{{ item }}"
        state: present
      with_items:
        - 'deb http://nginx.org/packages/ubuntu {{ ansible_distribution_release }} nginx'

    - name: Update repositories cache and install packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - wget
        - zsh
        - nginx

    - name: Copy config file
      copy:
        src: "{{ playbook_dir }}/../files/default.conf"
        dest: /etc/nginx/conf.d/
        backup: yes

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /var/www
        state: directory

    - name: Download index.html
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/xUndero/ansible_test/master/files/index.html
        dest: /var/www/
      notify:
        - nginx_restart

    - name: Set fs.file-max
      sysctl:
        name: fs.file-max
        value: "1204000"
        sysctl_set: yes

    - name: Set somaxconn
      sysctl:
        name: net.core.somaxconn
        value: "65535"
        sysctl_set: yes

    - name: Set up multiple authorized keys
      authorized_key:
        user: root
        state: present
        key: '{{ item }}'
      with_file:
        - "/home/user1/.ssh/id_rsa.pub"
        - "/home/user2/.ssh/id_rsa.pub"
      ignore_errors: yes

  handlers:
    - name: nginx_restart
      service: name=nginx state=restarted
